spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: securityuser
    password: fhEh1emd!!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false